export const STARTUP_LOAD_GAME: string = "STARTUP_LOAD_GAME";
export const GET_PIECES_STRENGTH: string = "GET_PIECES_STRENGTH";
export const SELECT_PIECE: string = "SELECT_PIECE";
export const CALCULATE_POSSIBLE_MOVES: string = "CALCULATE_POSSIBLE_MOVES";
export const PIECE_MOVE: string = "PIECE_MOVE";
export const UPDATE_CURRENT_ARRANGEMENT_SEQ_NUM: string =
  "UPDATE_CURRENT_ARRANGEMENT_SEQ_NUM";
export const GET_PIECES_STRENGTH: string = "GET_PIECES_STRENGTH";
