const pieces = [
  {
    name: "super pawn",
    code: "sp",
    img: "",
    movement: {
      code: "square-directional",
      possibleMoves: ["fl", "f", "ff", "fr"],
      attackMoves: ["fl", "f", "ff", "fr"],
      attackSameAsMove: true,
      canJump: false,
    },
    promotion: {
      to: "psp",
      condition: "last row",
      conditionCode: "lr",
    },
  },
  {
    name: "promoted super pawn",
    code: "psp",
    img: "",
    movement: {
      code: "square-directional",
      possibleMoves: ["fl", "f", "ff", "fr", "l", "r", "bl", "b", "bb", "br"],
      attackMoves: ["fl", "f", "ff", "fr", "l", "r", "bl", "b", "bb", "br"],
      attackSameAsMove: true,
      canJump: false,
    },
    promotion: {},
  },
  {
    name: "knight",
    code: "n",
    img: "",
    movement: {
      code: "square-directional",
      possibleMoves: ["ffl", "ffr", "fll", "frr", "bll", "brr", "bbl", "bbr"],
      attackMoves: ["ffl", "ffr", "fll", "frr", "bll", "brr", "bbl", "bbr"],
      attackSameAsMove: true,
      canJump: true,
    },
    promotion: {},
  },
  {
    name: "king",
    code: "k",
    img: "",
    movement: {
      code: "square-directional",
      possibleMoves: ["fl", "f", "fr", "l", "r", "bl", "b", "br"],
      attackMoves: ["fl", "f", "fr", "l", "r", "bl", "b", "br"],
      attackSameAsMove: true,
      canJump: false,
    },
    promotion: {},
  },
  {
    name: "pawn",
    code: "p",
    img: "",
    movement: {
      code: "square-directional",
      possibleMoves: ["f"],
      attackMoves: ["fl", "fr"],
      attackSameAsMove: false,
      canJump: false,
    },
    promotion: {
      to: "q",
      condition: "last row",
      conditionCode: "lr",
    },
  },
  {
    name: "rook",
    code: "r",
    img: "",
    movement: {
      code: "square-directional",
      possibleMoves: ["f+", "b+", "l+", "r+"],
      attackMoves: ["f+", "b+", "l+", "r+"],
      attackSameAsMove: true,
      canJump: false,
    },
    promotion: {},
  },
  {
    name: "bishop",
    code: "b",
    img: "",
    movement: {
      code: "square-directional",
      possibleMoves: ["fl+", "fr+", "bl+", "br+"],
      attackMoves: ["fl+", "fr+", "bl+", "br+"],
      attackSameAsMove: true,
      canJump: false,
    },
    promotion: {},
  },
  {
    name: "queen",
    code: "q",
    img: "",
    movement: {
      code: "square-directional",
      possibleMoves: ["fl+", "f+", "fr+", "l+", "r+", "bl+", "b+", "br+"],
      attackMoves: ["fl+", "f+", "fr+", "l+", "r+", "bl+", "b+", "br+"],
      attackSameAsMove: true,
      canJump: false,
    },
    promotion: {},
  },
  {
    name: "jumping queen",
    code: "jq",
    img: "",
    movement: {
      code: "square-directional",
      possibleMoves: ["fl+", "f+", "fr+", "l+", "r+", "bl+", "b+", "br+"],
      attackMoves: ["fl+", "f+", "fr+", "l+", "r+", "bl+", "b+", "br+"],
      attackSameAsMove: true,
      canJump: true,
    },
    promotion: {},
  },
];

const boards = [
  {
    name: "chess board",
    code: "chess",
    shape: "square",
    size: [8, 8],
    numSpaces: 64,
    spaceShape: "square",
    rowCodes: ["1", "2", "3", "4", "5", "6", "7", "8"],
    columnCodes: ["a", "b", "c", "d", "e", "f", "g", "h"],
    rowNums: [...Array(8).keys()],
    columnNums: [...Array(8).keys()],
  },
];

const gameTypes = [
  {
    name: "gameType1",
    code: "sps",
    boardCode: "chess",
    pieceCodes: ["sp", "psp"],
    startingPiecePositions: [
      "Asp-a1",
      "Asp-b1",
      "Asp-c1",
      "Asp-d1",
      "Asp-e1",
      "Asp-f1",
      "Asp-g1",
      "Asp-h1",
      "Bsp-a8",
      "Bsp-b8",
      "Bsp-c8",
      "Bsp-d8",
      "Bsp-e8",
      "Bsp-f8",
      "Bsp-g8",
      "Bsp-h8",
    ],
    settings: {
      winCondition: { type: "annihilation" },
    },
  },
  {
    name: "knight and king mayhem",
    code: "kn",
    boardCode: "chess",
    pieceCodes: ["n", "k"],
    startingPiecePositions: [
      "An-c2",
      "An-d2",
      "An-e2",
      "An-f2",
      "Ak-d1",
      "Ak-e1",
      "Bn-c7",
      "Bn-d7",
      "Bn-e7",
      "Bn-f7",
      "Bk-d8",
      "Bk-e8",
    ],
    settings: {
      winCondition: { type: "annihilation" },
    },
  },
  {
    name: "king queen rook bishop fun",
    code: "kqrb",
    boardCode: "chess",
    pieceCodes: ["k", "r", "q", "b"],
    startingPiecePositions: [
      "Ab-c2",
      "Ar-d2",
      "Aq-e2",
      "Ab-f2",
      "Ak-d1",
      "Ak-e1",
      "Bb-c7",
      "Br-d7",
      "Bq-e7",
      "Bb-f7",
      "Bk-d8",
      "Bk-e8",
    ],
    settings: {
      winCondition: { type: "annihilation" },
    },
  },
  {
    name: "playing with pawns",
    code: "pwp",
    boardCode: "chess",
    pieceCodes: ["k", "p"],
    startingPiecePositions: [
      "Ap-a2",
      "Ap-b2",
      "Ap-c2",
      "Ap-d2",
      "Ap-e2",
      "Ap-f2",
      "Ap-g2",
      "Ap-h2",
      "Ak-e1",
      "Bp-a7",
      "Bp-b7",
      "Bp-c7",
      "Bp-d7",
      "Bp-e7",
      "Bp-f7",
      "Bp-g7",
      "Bp-h7",
      "Bk-d8",
    ],
    settings: {
      winCondition: { type: "annihilation" },
    },
  },
];

const initialState = {
  count: 0,
  currentWinner: "",
  gameBoardAndPiecesSequence: [],
  gameBoardAndPiecesMoves: [],
  currentBoardAndPiecesSeqNum: 0,
  newMove: {
    piece: "",
    from: "",
    to: "",
  },
  boards: boards,
  pieces: pieces,
  currentGameTypeCode: "pwp",
  gameTypes: gameTypes,
};

export default initialState;
